// This code was generated by a tool. Changes will be lost.
using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
[assembly: AssemblyCompany("Cloud Foundry Foundation")]
[assembly: AssemblyCopyright("© 2015 Cloud Foundry Foundation")]
[assembly: AssemblyProduct("Cloud Foundry")]
[assembly: AssemblyVersion("0.0.0")]
[assembly: AssemblyFileVersion("0.0.0")]
[assembly: AssemblyInformationalVersion("DevLocal")]
