//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: log_message.proto
namespace logmessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogMessage")]
  public partial class LogMessage : global::ProtoBuf.IExtensible
  {
    public LogMessage() {}
    
    private byte[] _message;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private logmessage.LogMessage.MessageType _message_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public logmessage.LogMessage.MessageType message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private string _app_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"app_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string app_id
    {
      get { return _app_id; }
      set { _app_id = value; }
    }
    private string _source_id = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"source_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string source_id
    {
      get { return _source_id; }
      set { _source_id = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _drain_urls = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(7, Name=@"drain_urls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> drain_urls
    {
      get { return _drain_urls; }
    }
  
    private string _source_name = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"source_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string source_name
    {
      get { return _source_name; }
      set { _source_name = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MessageType")]
    public enum MessageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OUT", Value=1)]
      OUT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR", Value=2)]
      ERR = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogEnvelope")]
  public partial class LogEnvelope : global::ProtoBuf.IExtensible
  {
    public LogEnvelope() {}
    
    private string _routing_key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"routing_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string routing_key
    {
      get { return _routing_key; }
      set { _routing_key = value; }
    }
    private byte[] _signature;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] signature
    {
      get { return _signature; }
      set { _signature = value; }
    }
    private logmessage.LogMessage _log_message;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"log_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public logmessage.LogMessage log_message
    {
      get { return _log_message; }
      set { _log_message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}